# Generated by Django 4.2 on 2025-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('TMP', 'Temperature'), ('HUM', 'Humidity'), ('MTN', 'Motion')], max_length=20)),
                ('value', models.FloatField(default=0.0)),
                ('time_change', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
