# Generated by Django 4.2 on 2025-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('LMP', 'Smart lamp'), ('SCT', 'Smart socket'), ('DMR', 'Dimmer'), ('CND', 'Conditioner'), ('HTR', 'Heater')], max_length=20)),
                ('status', models.FloatField(default=0.0)),
            ],
        ),
    ]
