# Generated by Django 4.2 on 2025-05-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
